WordPressPCL/WordPressClient.cs, WordPressPCLTests/UnitTest1.cs, WordPressPCLTests/Utility/ApiCredentials-sample.cs
- Get list of sticky posts
- Get list of posts by category id
- Get list of posts by tag id
- Get list of posts by author id
- Get list of posts by search term (aka "Search")
- respective tests
=> Added some juice

WordPressPCL/Utility/QueryBuilder.cs
Updated QueryBuilder to support "after" search parameter.
=> ListPostsAfter functionality #13

WordPressPCL/Client/CRUDOperation.cs, WordPressPCL/Client/Categories.cs, WordPressPCL/Client/Comments.cs, WordPressPCL/Client/Media.cs, WordPressPCL/Client/Pages.cs, WordPressPCL/Client/PostRevisions.cs, WordPressPCL/Client/Posts.cs, WordPressPCL/Client/Tags.cs, WordPressPCL/Client/Users.cs, WordPressPCL/Models/Comment.cs, WordPressPCL/Models/MediaItem.cs, WordPressPCL/Models/Page.cs, WordPressPCL/Models/Post.cs, WordPressPCL/Models/PostRevision.cs, WordPressPCL/Models/Term.cs, WordPressPCL/WordPressPCL.xml
Need retest
I test only post revisions and posts
=> fix issue with force deletion

WordPressPCL/Client/Media.cs, WordPressPCL/Client/Users.cs, WordPressPCL/WordPressPCL.xml, WordPressPCLTests/User_Tests.cs
Hope this is last and fix all issues
=> Fix user delete with reassign parameter & Fix media create

WordPressPCL/Client/CustomRequest.cs, WordPressPCL/WordPressClient.cs, WordPressPCL/WordPressPCL.xml, WordPressPCLTests/CustomRequests_Tests.cs
Add custom requests #33 
Add tests for custom requests for contact-form-7 (requires contact-form-7 to be installed)
=> Add custom requests

WordPressPCL/Utility/HttpHelper.cs, WordPressPCL/WordPressClient.cs, WordPressPCLTests/Utility/HttpHelper_Tests.cs
Adding Http response pre processing method to let developpers to clean the response before Deserialize it
This PR replace the PR #45 (cancelled)
=> Adding Http response pre processing method

WordPressPCL/Client/CRUDOperation.cs, WordPressPCL/Client/Comments.cs, WordPressPCL/Client/CustomRequest.cs, WordPressPCL/Client/Media.cs, WordPressPCL/Client/Pages.cs, WordPressPCL/Client/PostRevisions.cs, WordPressPCL/Client/PostStatuses.cs, WordPressPCL/Client/PostTypes.cs, WordPressPCL/Client/Posts.cs, WordPressPCL/Client/Taxonomies.cs, WordPressPCL/Client/Users.cs, WordPressPCL/WordPressClient.cs, WordPressPCLTests/User_Tests.cs
=> Remove unnecessary async/await calls

WordPressPCL/WordPressClient.cs, WordPressPCLTests/Basic_Tests.cs
Add logout method #56 
Add test for logout method
=> Add logout method

WordPressPCL/Models/CommentThreaded.cs, WordPressPCL/WordPressClient.cs, WordPressPCL/WordPressPCL.csproj, WordPressPCL/WordPressPCL.xml
NuGet Update to 1.2.1
Added JWT Getter & Setter
Added missing comments
=> Milesone 1.3

WordPressPCL/Client/Media.cs, WordPressPCL/WordPressClient.cs, WordPressPCL/WordPressPCL.xml, WordPressPCLTests/Media_Tests.cs
- Create Media from file for Net Standard 2.0 #30 
- Remove unused HttpClient in RequestJWToken method
=> Media Create for netdtansard 2.0

WordPressPCL/Models/Comment.cs
=> Add JsonProperty serialization attribute for comments model properties

WordPressPCL/Models/Enums.cs
=> Fix for issue #93

WordPressPCL/Utility/HttpHelper.cs, WordPressPCL/WordPressPCL.xml
=> make HttpClient static

WordPressPCL/Models/BadRequest.cs, WordPressPCL/Models/Exceptions.cs, WordPressPCL/Utility/HttpHelper.cs, WordPressPCL/WordPressPCL.xml, WordPressPCLTests/Basic_Tests.cs, WordPressPCLTests/ExceptionTests.cs, WordPressPCLTests/ListPosts_QueryBuilder_Tests.cs, WordPressPCLTests/Settings_Tests.cs, WordPressPCLTests/Utility/ClientHelper.cs, WordPressPCLTests/Utility/HttpHelper_Tests.cs
=> Throw exceptions from Httphelper

WordPressPCL.Tests.Selfhosted/Categories_Tests.cs, WordPressPCL.Tests.Selfhosted/Comments_Tests.cs, WordPressPCL.Tests.Selfhosted/CustomRequests_Tests.cs, WordPressPCL.Tests.Selfhosted/Media_Tests.cs, WordPressPCL.Tests.Selfhosted/Pages_Tests.cs, WordPressPCL.Tests.Selfhosted/PostRevisions_Tests.cs, WordPressPCL.Tests.Selfhosted/Posts_Tests.cs, WordPressPCL.Tests.Selfhosted/Tag_Tests.cs, WordPressPCL.Tests.Selfhosted/User_Tests.cs, WordPressPCL/Client/CRUDOperation.cs, WordPressPCL/Client/Comments.cs, WordPressPCL/Client/CustomRequest.cs, WordPressPCL/Client/Media.cs, WordPressPCL/Client/Pages.cs, WordPressPCL/Client/PostRevisions.cs, WordPressPCL/Client/Posts.cs, WordPressPCL/Client/Users.cs, WordPressPCL/Interfaces/IDeleteOperation.cs, WordPressPCL/Utility/HttpHelper.cs, WordPressPCL/WordPressPCL.xml
=> change delete request return value from HttpResponceMessage to bool

WordPressPCL.Tests.Hosted/Basic_Tests.cs, WordPressPCL.Tests.Hosted/WordPressPCL.Tests.Hosted.csproj, WordPressPCL.Tests.Selfhosted/WordPressPCL.Tests.Selfhosted.csproj, WordPressPCL/Models/Comment.cs, WordPressPCL/Models/Enums.cs, WordPressPCL/WordPressPCL.csproj, WordPressPCL/WordPressPCL.xml
#133 add DefaultValueHanling = Ignore to Comments Status property. Hold status is now default
update nuget packages
=> Fix comments create problem

WordPressPCL/Models/MediaSize.cs
According to #143 
in this case height and width of Size property can be null
=> Fix sizes deserialization error

WordPressPCL.Tests.Selfhosted/Utility/CapabilitiesJsonConverter_Tests.cs, WordPressPCL/Models/User.cs, WordPressPCL/Utility/CustomCapabilitiesJsonConverter.cs, WordPressPCL/WordPressPCL.xml
custom string to bool converter for capabilities fields #147
=> add custom json converter for capabilities fields

WordPressPCL/Utility/MimeTypeHelper.cs
Pull request from issue : https://github.com/wp-net/WordPressPCL/issues/162
=> Applications/octet-stream MIMEType format 

WordPressPCL/Client/Media.cs
The file handle's got not released after uploading the images. So e.g. removing after an upload was not possible.
=> Wrap file usage in using.

WordPressPCL.Tests.Selfhosted/User_Tests.cs, WordPressPCL/WordPressPCL.xml
replaced random number with guid to prevent failed tests due to duplicates
=> Fix User tests

WordPressPCL/Models/Enums.cs, WordPressPCL/Models/Page.cs, WordPressPCL/Models/Post.cs, WordPressPCL/WordPressPCL.xml
Found out this was missing, fixed for my project and shared :)
As per issue #177
=> added trash status (for post/page)

WordPressPCL.Tests.Selfhosted/Posts_Tests.cs, WordPressPCL/Utility/CategoriesQueryBuilder.cs, WordPressPCL/Utility/CommentsQueryBuilder.cs, WordPressPCL/Utility/MediaQueryBuilder.cs, WordPressPCL/Utility/PagesQueryBuilder.cs, WordPressPCL/Utility/PostsQueryBuilder.cs, WordPressPCL/Utility/TagsQueryBuilder.cs, WordPressPCL/Utility/UsersQueryBuilder.cs, WordPressPCL/WordPressPCL.xml
=> added test for trashed posts

WordPressPCL/Models/Page.cs
=> Added password field to pages model.

WordPressPCL.Tests.Selfhosted/ExceptionTests.cs, WordPressPCL.Tests.Selfhosted/Settings_Tests.cs, WordPressPCL/Client/Settings.cs, WordPressPCL/WordPressClient.cs, WordPressPCL/WordPressPCL.xml
Refactored settings related methods in a separate Settings sub client.
=> Settings Sub Client

docs/I version 2.x/entities/users.md
=> Docs: Create application passwords

.editorconfig, .github/workflows/codeql-analysis.yml, .github/workflows/documentation.yml, .github/workflows/integration-tests.yml, .github/workflows/publish-nuget.yml, README.md, WordPressPCL.Tests.Hosted/WordPressPCL.Tests.Hosted.csproj, WordPressPCL.Tests.Selfhosted/Comments_Tests.cs, WordPressPCL.Tests.Selfhosted/Posts_Tests.cs, WordPressPCL.Tests.Selfhosted/User_Tests.cs, WordPressPCL.Tests.Selfhosted/WordPressPCL.Tests.Selfhosted.csproj, WordPressPCL/Client/CRUDOperation.cs, WordPressPCL/Client/CustomRequest.cs, WordPressPCL/Client/Media.cs, WordPressPCL/Client/PostRevisions.cs, WordPressPCL/Client/PostStatuses.cs, WordPressPCL/Client/PostTypes.cs, WordPressPCL/Client/Taxonomies.cs, WordPressPCL/Client/Users.cs, WordPressPCL/Interfaces/IQueryOperation.cs, WordPressPCL/Interfaces/IReadOperation.cs, WordPressPCL/WordPressPCL.csproj, WordPressPCL/WordPressPCL.xml
- updated readme
- fixed GetCurrentUserAsync naming #360 
- add optional ignoreDefaultPath on CustomRequest methods #354 
- Return Lists<> instead of IEnumerables<>
=> Fix namings, List return types

.github/workflows/integration-tests.yml, README.md, dev/docker-compose.yml, dev/install.md
Fixes CI errors such as https://github.com/wp-net/WordPressPCL/actions/runs/8558946061/job/23454569138?pr=367#step:5:14
See https://github.com/orgs/community/discussions/116610 for details
=> CI: Use Docker Compose V2

docs/I version 2.x/entities/posts.md
=> Docs: Update custom fields
